# Generated by Django 4.1.3 on 2022-11-26 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Digite o Modelo', max_length=100)),
                ('marca', models.TextField(help_text='Digite a marca')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Digite o valor', max_digits=9)),
                ('observacoes', models.TextField(help_text='Digite as Observações')),
                ('fotos', models.ImageField(upload_to='img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
