# Generated by Django 4.1.3 on 2022-11-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='fotos',
            field=models.ImageField(upload_to='MyCars/static/MyCars/img'),
        ),
    ]
